apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: web-version
        color: green
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: index-green-v1
---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    color: green
